### ISSUE TITLE
New api is not type safe

### ISSUE THREAD

**Issue by josemanuelp** [andogq/qubit#66]
The new API is not generating type-safe clients, even though the client is apparently being generated correctly.

![image](https://github.com/andogq/qubit/assets/6510893/ea2284b0-358d-4e70-b0e9-3e610b65ee53)

![image](https://github.com/andogq/qubit/assets/6510893/2aa1d325-1ef1-43fa-bde6-2c4b006cf281)

**Comment by andogq** [comment]
Could you please confirm what versions of `qubit` and `@qubit-rs/client` you're currently using?

- `qubit` should be `0.9.4`
- `@qubit-rs/client` should be `0.4.1`

**Comment by josemanuelp** [comment]
Thanks for your response and hard work.

Yes! I'm using both versions.

My config files:

package.json:
```json
{
  "name": "test_bindings",
  "version": "1.0.0",
  "description": "",
  "main": "dist/main.js",
  "scripts": {
    "start": "node dist/main.js",
    "build": "tsc",
    "watch": "tsc --watch",
    "clean": "rm -rf dist"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^5.5.2"
  },
  "dependencies": {
    "@qubit-rs/client": "^0.4.1"
  }
}
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ES2022",
    "moduleResolution": "Bundler",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

Cargo.toml:
```toml
[package]
name = "cli"
description = "test project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.7", features = ["derive", "env"] }
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["time"] }
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
qubit = "0.9.4"
futures = "0.3.30"
axum = "0.7.5"
hyper = { version = "1.3.1", features = ["server"] }
ts-rs = "8.1.0"
```
